services:
  - type: web
    name: school-management-system
    env: python
    plan: free
    root: school-management-system
    branch: master
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py bootstrap_superadmin && gunicorn bjs_management.wsgi:application
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: ALLOWED_HOSTS
        value: '127.0.0.1,localhost'
      - key: BOOTSTRAP_SUPERADMIN
        value: 'False'
      - key: BOOTSTRAP_SUPERADMIN_USERNAME
        value: 'admin'
      - key: BOOTSTRAP_SUPERADMIN_PASSWORD
        fromSecret: BOOTSTRAP_SUPERADMIN_PASSWORD
      - key: BOOTSTRAP_SUPERADMIN_EMAIL
        value: 'admin@example.com'
      - key: TWILIO_ACCOUNT_SID
        fromSecret: TWILIO_ACCOUNT_SID
      - key: TWILIO_AUTH_TOKEN
        fromSecret: TWILIO_AUTH_TOKEN
      - key: TWILIO_PHONE_NUMBER
        value: '+15017122661'
      - key: DEFAULT_FROM_EMAIL
        value: 'webmaster@bitendejuniorschool.com'
