# Generated by Django 6.0.3 on 2026-03-09 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="data",
        ),
        migrations.AddField(
            model_name="timetable",
            name="cells",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="timetable",
            name="slots",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="sections",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="student",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="home_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="religion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("admin", "Admin"),
                            ("bursar", "Bursar"),
                            ("reception", "Reception"),
                            ("teacher", "Teacher"),
                            ("parent", "Parent"),
                            ("student", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("avatar", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
