# Generated by Django 6.0.3 on 2026-03-12 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_timetable_data_timetable_cells_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term_number', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_break_days', models.IntegerField(default=0)),
                ('auto_generate_invoices_on_start', models.BooleanField(default=False)),
                ('sms_parents_on_start', models.BooleanField(default=False)),
                ('open_mark_entry_on_start', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='previous_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_from_previous_class', to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='promotion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='promotion_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='promotion_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('repeating', 'Repeating'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdrawn', 'Withdrawn'), ('alumnus', 'Alumnus'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AlumniRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='graduation_certificates/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('promote', 'Promote'), ('repeat_year', 'Repeat Year'), ('graduate', 'Graduate'), ('transfer_out', 'Transfer Out'), ('withdraw', 'Withdraw')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to_class', to='school.schoolclass')),
                ('old_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from_class', to='school.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
