# Generated by Django 6.0.3 on 2026-03-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_idcounter_student_conduct_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('google_oauth', 'Google OAuth'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Mobile Money'), ('twilio_sms', 'Twilio SMS'), ('email_smtp', 'Email SMTP')], max_length=50, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
