# Generated by Django 6.0.3 on 2026-03-13 10:01

from django.db import migrations
from django.db.migrations.operations.models import RenameIndex


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_payment'),
    ]

    operations = [
        RenameIndex(
            model_name='payment',
            new_name='school_paym_receive_aa2f7b_idx',
            old_name='school_payme_received_c6b451_idx',
        ),
        RenameIndex(
            model_name='payment',
            new_name='school_paym_method_792cf5_idx',
            old_name='school_payme_method_5f1241_idx',
        ),
        RenameIndex(
            model_name='payment',
            new_name='school_paym_status_a93a82_idx',
            old_name='school_payme_status_0c0ae2_idx',
        ),
    ]
