# Generated by Codex on 2026-03-13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_rename_school_payme_received_c6b451_idx_school_paym_receive_aa2f7b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="academic_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="term_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["academic_year", "term_number"], name="school_paym_yearterm_idx"),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("academic_year", models.IntegerField()),
                ("term_number", models.IntegerField(choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")])),
                ("amount_due", models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ("status", models.CharField(choices=[("unpaid", "Unpaid"), ("partial", "Partial"), ("paid", "Paid")], default="unpaid", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="school.student")),
            ],
            options={
                "unique_together": {("student", "academic_year", "term_number")},
                "indexes": [
                    models.Index(fields=["academic_year", "term_number"], name="school_invoice_yearterm_idx"),
                    models.Index(fields=["status"], name="school_invoice_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("audience_roles", models.JSONField(blank=True, default=list, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

