# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_invoice_event_and_payment_term_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=80, unique=True)),
                ("value", models.JSONField(blank=True, default=dict, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

