# Generated by Django 6.0.3 on 2026-03-13 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.models import RenameIndex


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Scan')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendanceQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        RenameIndex(
            model_name='invoice',
            new_name='school_invo_academi_e39042_idx',
            old_name='school_invoice_yearterm_idx',
        ),
        RenameIndex(
            model_name='invoice',
            new_name='school_invo_status_a565b1_idx',
            old_name='school_invoice_status_idx',
        ),
        RenameIndex(
            model_name='payment',
            new_name='school_paym_academi_438ee7_idx',
            old_name='school_paym_yearterm_idx',
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='service_name',
            field=models.CharField(choices=[('google_oauth', 'Google OAuth'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Mobile Money'), ('twilio_sms', 'Twilio SMS'), ('email_smtp', 'Email SMTP'), ('openai', 'OpenAI (AI Key)')], max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_teacher_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='school.teacher'),
        ),
        migrations.AddField(
            model_name='teacherattendanceqrtoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date'], name='school_teac_date_9b2b61_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['status'], name='school_teac_status_615195_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date')},
        ),
        migrations.AddIndex(
            model_name='teacherattendanceqrtoken',
            index=models.Index(fields=['date'], name='school_teac_date_245310_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendanceqrtoken',
            index=models.Index(fields=['expires_at'], name='school_teac_expires_e0ffdd_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendanceqrtoken',
            index=models.Index(fields=['is_active'], name='school_teac_is_acti_6528a7_idx'),
        ),
    ]
