# Generated by Django 6.0.3 on 2026-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_userprofile_notification_prefs_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrator'), ('headteacher', 'Headteacher'), ('deputy', 'Deputy Headteacher'), ('dos', 'Director of Studies (DOS)'), ('bursar', 'Bursar'), ('reception', 'Reception'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20),
        ),
    ]
