# Generated by Django 6.0.3 on 2026-03-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_event_image_url_userprofile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='last_verify_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='last_verify_extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='last_verify_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
