# Generated by Django 6.0.3 on 2026-03-15 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_apicredential_last_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredential',
            name='service_name',
            field=models.CharField(choices=[('google_oauth', 'Google OAuth'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Mobile Money'), ('twilio_sms', 'Twilio SMS'), ('email_smtp', 'Email SMTP'), ('openai', 'OpenAI (AI Key)'), ('gemini', 'Google Gemini (AI Key)')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='school_subj_name_880daa_idx'), models.Index(fields=['is_active'], name='school_subj_is_acti_0849d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('test', 'Test'), ('exam', 'Exam'), ('notes', 'Notes')], default='test', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for printing'), ('printed', 'Printed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_drafts', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_documents', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='school_docu_status_7ae5b4_idx'), models.Index(fields=['created_by', 'created_at'], name='school_docu_created_990866_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='school.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='school.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['school_class', 'is_active'], name='school_clas_school__08c7e3_idx'), models.Index(fields=['subject', 'is_active'], name='school_clas_subject_60f40f_idx')],
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
