# Generated by Django 6.0.3 on 2026-03-15 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_userprofile_must_change_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted To Reception'), ('printed', 'Printed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slots',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school_class', 'section')},
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school_class', 'section'], name='school_time_school__024f0f_idx'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_exam_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='school.teacher'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['status', 'created_at'], name='school_exam_status_739a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['school_class', 'section'], name='school_exam_school__f519be_idx'),
        ),
    ]
