# Generated by Django 6.0.3 on 2026-03-15 14:24

from decimal import Decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_teacher_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term_number', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('kind', models.CharField(choices=[('discount', 'Discount'), ('waiver', 'Waiver'), ('penalty', 'Late Penalty'), ('correction', 'Correction')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_adjustments', to='school.student')),
            ],
            options={
                'indexes': [models.Index(fields=['academic_year', 'term_number'], name='school_invo_academi_148e7f_idx'), models.Index(fields=['student', 'academic_year', 'term_number'], name='school_invo_student_61e470_idx'), models.Index(fields=['kind'], name='school_invo_kind_fbcf67_idx'), models.Index(fields=['is_active'], name='school_invo_is_acti_d683e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='parent', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guardian_links', to=settings.AUTH_USER_MODEL)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='school.student')),
            ],
            options={
                'indexes': [models.Index(fields=['parent_user', 'is_active'], name='school_stud_parent__20be97_idx'), models.Index(fields=['student', 'is_active'], name='school_stud_student_d62c71_idx')],
                'unique_together': {('parent_user', 'student')},
            },
        ),
    ]
