# Generated by Django 6.0.3 on 2026-03-16 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_invoice_results_block_reason_invoice_results_blocked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('admission_letter', 'Admission Letter'), ('student_credentials', 'Student Credentials'), ('parent_credentials', 'Parent Credentials'), ('teacher_credentials', 'Teacher Credentials'), ('report_card', 'Report Card')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('printed', 'Printed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('wiped_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printqueue_printed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printqueue_requested', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='school_prin_status_9ed9f8_idx'), models.Index(fields=['kind', 'status'], name='school_prin_kind_380b8d_idx'), models.Index(fields=['expires_at'], name='school_prin_expires_2ed12b_idx')],
            },
        ),
    ]
