# Generated by Django 6.0.3 on 2026-03-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_printqueueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_assignments', to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
