# Generated by Django 6.0.3 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_teacher_class_teacher_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredential',
            name='service_name',
            field=models.CharField(choices=[('google_oauth', 'Google OAuth'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Mobile Money'), ('twilio_sms', 'Twilio SMS'), ('email_smtp', 'Email SMTP'), ('gmail_smtp', 'Gmail SMTP (App Password)'), ('megasms', 'MegaSMS Uganda (SMS Gateway)'), ('zapier_webhook', 'Zapier Webhook (Automation)'), ('openai', 'OpenAI (AI Key)'), ('gemini', 'Google Gemini (AI Key)')], max_length=50, unique=True),
        ),
    ]
