# Generated by Django 6.0.3 on 2026-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_apicredential_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printqueueitem',
            name='kind',
            field=models.CharField(choices=[('admission_letter', 'Admission Letter'), ('student_credentials', 'Student Credentials'), ('parent_credentials', 'Parent Credentials'), ('teacher_credentials', 'Teacher Credentials'), ('staff_credentials', 'Staff Credentials'), ('report_card', 'Report Card')], max_length=40),
        ),
    ]
