# Generated by Django 6.0.3 on 2026-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_alter_printqueueitem_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('login_2fa', 'Login 2FA'), ('new_device_login', 'New Device Login'), ('teacher_credential', 'Teacher Credential'), ('parent_credential', 'Parent Credential')], max_length=50),
        ),
    ]
