# Generated by Django 6.0.3 on 2026-04-07 07:02

from decimal import Decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_otp_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term_number', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('promise_date', models.DateField(default=django.utils.timezone.localdate)),
                ('promised_for', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('kept', 'Kept'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_promises', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_promises', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('term_number', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('title', models.CharField(default='Fee installment plan', max_length=160)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_installment_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installment_plans', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='school.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school.installmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='FeeReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(blank=True, null=True)),
                ('term_number', models.IntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In App'), ('manual', 'Manual')], default='sms', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='sent', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=160, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_reminders', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_reminders', to='school.invoice')),
                ('promise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='school.feepromise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_reminders', to='school.student')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='school.installmentplan')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='school.installmentplanitem')),
            ],
        ),
        migrations.AddField(
            model_name='feepromise',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_promises', to='school.installmentplanitem'),
        ),
        migrations.CreateModel(
            name='ResultsHoldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('held', 'Held'), ('released', 'Released')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('acted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_hold_actions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_logs', to='school.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='CashbookClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed')], default='closed', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cash_received_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('non_cash_received_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('approved_expense_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('expected_cash_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('counted_cash_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deposit_batch_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_count', models.IntegerField(default=0)),
                ('expense_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_closes', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cashbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['close_date', 'status'], name='school_cash_close_d_38a2d0_idx'), models.Index(fields=['cashier', 'close_date'], name='school_cash_cashier_c8302b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['student', 'academic_year', 'term_number'], name='school_inst_student_32157f_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['status', 'start_date'], name='school_inst_status_daa0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplanitem',
            index=models.Index(fields=['plan', 'due_date'], name='school_inst_plan_id_296656_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplanitem',
            index=models.Index(fields=['status', 'due_date'], name='school_inst_status_08d313_idx'),
        ),
        migrations.AddIndex(
            model_name='feereminderlog',
            index=models.Index(fields=['student', 'created_at'], name='school_feer_student_172ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='feereminderlog',
            index=models.Index(fields=['academic_year', 'term_number'], name='school_feer_academi_802129_idx'),
        ),
        migrations.AddIndex(
            model_name='feereminderlog',
            index=models.Index(fields=['channel', 'status'], name='school_feer_channel_2f31d4_idx'),
        ),
        migrations.AddIndex(
            model_name='feepromise',
            index=models.Index(fields=['student', 'academic_year', 'term_number'], name='school_feep_student_9ada9a_idx'),
        ),
        migrations.AddIndex(
            model_name='feepromise',
            index=models.Index(fields=['status', 'promised_for'], name='school_feep_status_c2bc36_idx'),
        ),
        migrations.AddIndex(
            model_name='resultsholdlog',
            index=models.Index(fields=['invoice', 'acted_at'], name='school_resu_invoice_364829_idx'),
        ),
        migrations.AddIndex(
            model_name='resultsholdlog',
            index=models.Index(fields=['action', 'acted_at'], name='school_resu_action_6e8dec_idx'),
        ),
    ]
