# Generated by Django 6.0.3 on 2026-04-07 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_feepromise_installmentplan_installmentplanitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentialHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('google_oauth', 'Google OAuth'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Mobile Money'), ('twilio_sms', 'Twilio SMS'), ('email_smtp', 'Email SMTP'), ('gmail_smtp', 'Gmail SMTP (App Password)'), ('megasms', 'MegaSMS Uganda (SMS Gateway)'), ('zapier_webhook', 'Zapier Webhook (Automation)'), ('openai', 'OpenAI (AI Key)'), ('gemini', 'Google Gemini (AI Key)')], max_length=50)),
                ('is_ok', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-verified_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='school.student'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', 'created_at'], name='school_noti_student_74df1e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['school_class', 'created_at'], name='school_noti_school__d56f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_key', 'created_at'], name='school_noti_event_k_c4c7f9_idx'),
        ),
        migrations.AddField(
            model_name='apicredentialhealthlog',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_logs', to='school.apicredential'),
        ),
        migrations.AddField(
            model_name='apicredentialhealthlog',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_health_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apicredentialhealthlog',
            index=models.Index(fields=['service_name', 'verified_at'], name='school_apic_service_801f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='apicredentialhealthlog',
            index=models.Index(fields=['credential', 'verified_at'], name='school_apic_credent_23a2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='apicredentialhealthlog',
            index=models.Index(fields=['is_ok', 'verified_at'], name='school_apic_is_ok_d07232_idx'),
        ),
    ]
