# Generated by Django 6.0.3 on 2026-04-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_apicredentialhealthlog_notification_event_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdraft',
            name='kind',
            field=models.CharField(choices=[('test', 'Test'), ('exam', 'Exam'), ('notes', 'Notes'), ('letter', 'Letter'), ('notice', 'Notice'), ('message', 'Message')], default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='printqueueitem',
            name='kind',
            field=models.CharField(choices=[('admission_letter', 'Admission Letter'), ('student_credentials', 'Student Credentials'), ('parent_credentials', 'Parent Credentials'), ('mail_merge_letter', 'Mail Merge Letter'), ('teacher_credentials', 'Teacher Credentials'), ('staff_credentials', 'Staff Credentials'), ('report_card', 'Report Card')], max_length=40),
        ),
    ]
