# Generated by Django 6.0.4 on 2026-04-12 10:49

import django.db.models.deletion
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_documentdraft_kind_alter_printqueueitem_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('audience', models.CharField(default='guardians', max_length=20)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('partially_failed', 'Partially Failed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('retry_limit', models.PositiveIntegerField(default=2)),
                ('retry_delay_minutes', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('message_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('retry_pending', 'Retry Pending'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('opened', 'Opened'), ('confirmed', 'Confirmed'), ('replied', 'Replied')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ack_token', models.CharField(db_index=True, default=school.models._default_ack_token, max_length=80, unique=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_document_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='footer_preset',
            field=models.CharField(choices=[('standard', 'Standard Footer'), ('finance', 'Finance Footer'), ('academic', 'Academic Footer'), ('minimal', 'Minimal Footer')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='header_preset',
            field=models.CharField(choices=[('standard', 'Standard School Header'), ('finance', 'Finance Header'), ('academic', 'Academic Header'), ('minimal', 'Minimal Header')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='include_school_stamp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='include_signature_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='library_scope',
            field=models.CharField(choices=[('all', 'All Staff'), ('teacher', 'Teacher Library'), ('admin', 'Admin Library'), ('bursar', 'Bursar Library'), ('reception', 'Reception Library')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='school.documentdraft'),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_document_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='template_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='workflow_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentdraft',
            index=models.Index(fields=['template_key', 'version_number'], name='school_docu_templat_435e17_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdraft',
            index=models.Index(fields=['workflow_status', 'library_scope'], name='school_docu_workflo_4ee2cf_idx'),
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='school.documentdraft'),
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student'),
        ),
        migrations.AddField(
            model_name='communicationdelivery',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='school.communicationcampaign'),
        ),
        migrations.AddField(
            model_name='communicationdelivery',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.student'),
        ),
        migrations.AddIndex(
            model_name='communicationcampaign',
            index=models.Index(fields=['status', 'scheduled_for'], name='school_comm_status_f60158_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationcampaign',
            index=models.Index(fields=['created_by', 'created_at'], name='school_comm_created_52b4af_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationdelivery',
            index=models.Index(fields=['campaign', 'status'], name='school_comm_campaig_648df7_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationdelivery',
            index=models.Index(fields=['next_attempt_at', 'status'], name='school_comm_next_at_2aac5f_idx'),
        ),
    ]
