# pyright: reportAttributeAccessIssue=false
# Generated by Django 6.0.5 on 2026-05-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_attendance_and_timetable_term_linking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetable',
            new_name='school_time_academi_55d1e0_idx',
            old_name='school_timet_academi_4e93b0_idx',
        ),
    ]
