# pyright: reportAttributeAccessIssue=false
# Generated by Django 6.0.5 on 2026-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_enhanced_grading_and_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingscale',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.RenameIndex(
            model_name='academiccalendarevent',
            new_name='school_acad_academi_195779_idx',
            old_name='school_acad_academi_f1a14c_idx',
        ),
        migrations.RenameIndex(
            model_name='academiccalendarevent',
            new_name='school_acad_event_t_77124d_idx',
            old_name='school_acad_event_t_905b96_idx',
        ),
        migrations.RenameIndex(
            model_name='examtype',
            new_name='school_exam_is_acti_dbea81_idx',
            old_name='school_exam_is_acti_f5dc47_idx',
        ),
        migrations.RenameIndex(
            model_name='gradingscale',
            new_name='school_grad_is_defa_23147b_idx',
            old_name='school_grad_is_defa_9aa3e6_idx',
        ),
        migrations.RenameIndex(
            model_name='gradingscale',
            new_name='school_grad_templat_e48cb9_idx',
            old_name='school_grad_template_68bb9b_idx',
        ),
        migrations.RenameIndex(
            model_name='staffpayroll',
            new_name='school_staf_academi_466368_idx',
            old_name='school_staf_academi_20dc8c_idx',
        ),
        migrations.RenameIndex(
            model_name='staffpayroll',
            new_name='school_staf_paid_da_9bbc64_idx',
            old_name='school_staf_paid_da_cad60d_idx',
        ),
        migrations.RenameIndex(
            model_name='studentdebtrecord',
            new_name='school_stud_student_4bd88d_idx',
            old_name='school_stud_student_596f37_idx',
        ),
        migrations.RenameIndex(
            model_name='studentdebtrecord',
            new_name='school_stud_academi_fdd9ac_idx',
            old_name='school_stud_academi_251a88_idx',
        ),
        migrations.RenameIndex(
            model_name='teachersalary',
            new_name='school_teac_teacher_0dde54_idx',
            old_name='school_teac_teacher_7a4451_idx',
        ),
        migrations.RenameIndex(
            model_name='teachersalary',
            new_name='school_teac_payment_4d6afa_idx',
            old_name='school_teac_payment_52121d_idx',
        ),
        migrations.AlterField(
            model_name='gradingscale',
            name='scale_data',
            field=models.JSONField(default=list, help_text='[{"grade": "A+", "min_score": 90, "max_score": 100, "gpa_points": 4.0, "status": "Pass", "implication": "Promote / Graduate"}]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('director', 'Director/Head Director'), ('admin', 'Administrator'), ('headteacher', 'Headteacher'), ('deputy', 'Deputy Headteacher'), ('dos', 'Director of Studies (DOS)'), ('bursar', 'Bursar'), ('reception', 'Reception'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20),
        ),
    ]
