"""
Django settings for bjs_management project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from importlib import import_module
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from decouple import config  # Added for environment variables
import os  # Added for path operations


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _read_repo_env_value(name: str):
    """
    Read a raw value from the repository .env file.
    Used as a fallback when a machine-level environment variable is present
    but contains a non-boolean value like "release".
    """
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return None
    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        if key.strip() == name:
            return value.strip()
    return None


def env_bool(name: str, default: bool = False) -> bool:
    """
    More tolerant boolean parsing than decouple's strict cast=bool.
    Prevents crashes when env values are non-standard (e.g. "release").
    """
    raw = config(name, default=None)
    if raw is None:
        return default
    s = str(raw).strip().lower()
    if s in ("1", "true", "t", "yes", "y", "on"):
        return True
    if s in ("0", "false", "f", "no", "n", "off"):
        return False
    repo_raw = _read_repo_env_value(name)
    if repo_raw is not None:
        repo_s = str(repo_raw).strip().lower()
        if repo_s in ("1", "true", "t", "yes", "y", "on"):
            return True
        if repo_s in ("0", "false", "f", "no", "n", "off"):
            return False
    return default

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)

DEV_FALLBACK_SECRET_KEY = "bjs-dev-only-6f5aa0fb9f1a4f6a8c8b2ea5c7c1f34a4c217d5f8d6b9d2a"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=DEV_FALLBACK_SECRET_KEY) # Using decouple

if not DEBUG and SECRET_KEY == DEV_FALLBACK_SECRET_KEY:
    raise ImproperlyConfigured(
        'A production SECRET_KEY must be set in the environment. '
        'Do not use the development fallback secret in production.'
    )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])
if DEBUG:
    for host in ('127.0.0.1', 'localhost', 'testserver'):
        if host not in ALLOWED_HOSTS:  # type: ignore[operator]
            ALLOWED_HOSTS.append(host)  # type: ignore[attr-defined]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sites",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "school",
    # Allauth apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # 'debug_toolbar', # Optional: for development debugging
]

try:
    import whitenoise  # type: ignore  # noqa: F401
    HAS_WHITENOISE = True
except Exception:
    HAS_WHITENOISE = False

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware", # Placed before allauth.account.middleware.AccountMiddleware
    "allauth.account.middleware.AccountMiddleware", # Added for django-allauth
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "bjs_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.csrf",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bjs_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Allow overriding the DATABASE via DATABASE_URL (Render, Railway, Fly.io,
# Heroku, Neon, Supabase, local Postgres, or sqlite:///path/db.sqlite3).
database_url = config("DATABASE_URL", default=None)
if database_url:
    try:
        dj_database_url = import_module("dj_database_url")
        DATABASES["default"] = dj_database_url.parse(
            database_url,
            conn_max_age=config("DB_CONN_MAX_AGE", default=600, cast=int),
            ssl_require=env_bool("DB_SSL_REQUIRE", default=(not DEBUG)),
        )
    except Exception as exc:
        if not DEBUG:
            raise ImproperlyConfigured(
                "DATABASE_URL is set but could not be parsed. "
                "Check the provider database URL and required database driver."
            ) from exc
        import warnings
        warnings.warn(f"DATABASE_URL could not be parsed; falling back to local SQLite: {exc}")
elif not DEBUG and not env_bool("ALLOW_SQLITE_IN_PRODUCTION", default=False):
    raise ImproperlyConfigured(
        "DATABASE_URL must be set when DEBUG=False. "
        "Use a hosted PostgreSQL DATABASE_URL or set ALLOW_SQLITE_IN_PRODUCTION=True only for a temporary test."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 10},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "school.validators.StrongSchoolPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = config('TIME_ZONE', default="Africa/Nairobi")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "school" / "static",
]

# Use compressed manifest storage in production for better caching and integrity
if not DEBUG and HAS_WHITENOISE:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Optional: support S3 media storage when `USE_S3` is enabled in the environment.
USE_S3 = env_bool('USE_S3', default=False)
if USE_S3:
    try:
        # Lazy import to avoid hard dependency when not used
        from storages.backends.s3boto3 import S3Boto3Storage  # type: ignore

        AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
        AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
        AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
        AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='')

        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    except Exception:
        # If django-storages is not installed, fall back to local media but log a warning.
        import warnings
        warnings.warn('USE_S3 is true but django-storages is not available; falling back to local MEDIA_ROOT.')


# Keep CORS permissive for dev; production should be set explicitly via CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="",
    cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
)

# Security defaults (tighten automatically when DEBUG=False)
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = "same-origin"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True

# We read CSRF from a meta tag in the SPA, so the cookie can safely be HttpOnly.
CSRF_COOKIE_HTTPONLY = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=60 * 60 * 24 * 30, cast=int)  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = config(
        "CSRF_TRUSTED_ORIGINS",
        default="",
        cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
    )

# Email settings for password reset (for development, prints to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, uncomment and configure these:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@example.com'
# EMAIL_HOST_PASSWORD = 'your_email_password'
# DEFAULT_FROM_EMAIL = 'webmaster@yourdomain.com'

# Twilio Settings (for SMS)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') # Replace with your Account SID
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='your_auth_token') # Replace with your Auth Token
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='+15017122661') # Replace with your Twilio phone number

# Default email for sending (e.g., graduation certificates)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='webmaster@bitendejuniorschool.com')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': [ 'console', 'file' ],
            'level': 'INFO',
            'propagate': True,
        },
        'school': {
            'handlers': [ 'console', 'file' ],
            'level': 'INFO',
            'propagate': False,
        },
        'twilio': {
            'handlers': [ 'console', 'file' ],
            'level': 'INFO',
            'propagate': False,
        }
    }
}

# Allauth settings
AUTHENTICATION_BACKENDS = [
    # Needed for Django admin login
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1 # Required for django-allauth

# Allauth settings
LOGIN_REDIRECT_URL = '/' # Redirect to home page after login
ACCOUNT_LOGOUT_REDIRECT_URL = '/' # Redirect to home page after logout
# Deprecated allauth settings removed, using newer equivalents below

# Allauth settings (modern)
# `ACCOUNT_LOGIN_METHODS` is the replacement for the deprecated login settings.
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional' # or 'mandatory' for strict verification

# Social account providers default to environment; the active Google client_id/secret are provided
# at runtime via `SOCIALACCOUNT_ADAPTER` (see `school/adapters.py`) to avoid DB access during settings import.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=None),
            'secret': config('GOOGLE_CLIENT_SECRET', default=None),
            'key': '' # Not used
        }
    }
}

SOCIALACCOUNT_ADAPTER = 'school.adapters.APICredentialSocialAccountAdapter'

# DRF defaults: session-authenticated API, locked down by default.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Basic API throttling (cache-backed). Keep high enough for the SPA.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '600/min',
        'anon': '120/min',
    },
}
